//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        public int id_Administrador { get; set; }
        public string rut_Administrador { get; set; }
        public string nombre_Administrador { get; set; }
        public string apellidos_Administrador { get; set; }
        public string clave_Administrador { get; set; }
        public string estado_Administrador { get; set; }
    }
}
