//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CitaMedica
    {
        public int id_CitaMedica { get; set; }
        public System.DateTime fechaCita_CitaMedica { get; set; }
        public System.DateTime fechaSol_CitaMedica { get; set; }
        public string hora_CitaMedica { get; set; }
        public string estado_CitaMedica { get; set; }
        public Nullable<int> Paciente_idPaciente_CitaMedica { get; set; }
        public Nullable<int> Doctor_idDoctor_CitaMedica { get; set; }
        public Nullable<int> Secretario_idSecretaria_CitaMedica { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual Secretaria Secretaria { get; set; }
    }
}
