//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public Doctor()
        {
            this.CitaMedica = new HashSet<CitaMedica>();
            this.FichaMedica = new HashSet<FichaMedica>();
        }
    
        public int id_Doctor { get; set; }
        public string rut_Doctor { get; set; }
        public string nombres_Doctor { get; set; }
        public string apellidos_Doctor { get; set; }
        public string direccion_Doctor { get; set; }
        public string nTelefono_Doctor { get; set; }
        public System.DateTime fechaNac_Doctor { get; set; }
        public string clave_Doctor { get; set; }
        public string estado_Doctor { get; set; }
    
        public virtual ICollection<CitaMedica> CitaMedica { get; set; }
        public virtual ICollection<FichaMedica> FichaMedica { get; set; }
    }
}
