//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examen
    {
        public Examen()
        {
            this.ExamenXFicha = new HashSet<ExamenXFicha>();
        }
    
        public int id_Examen { get; set; }
        public string codigo_Examen { get; set; }
        public string descripcion_Examen { get; set; }
    
        public virtual ICollection<ExamenXFicha> ExamenXFicha { get; set; }
    }
}
